const CNAE_SEGMENTS: Record<number, string> = {
  1: 'Agropecuária',
  2: 'Agropecuária',
  3: 'Agropecuária',
  5: 'Mineração',
  6: 'Mineração',
  7: 'Mineração',
  8: 'Mineração',
  9: 'Mineração',
  10: 'Indústria',
  11: 'Indústria',
  12: 'Indústria',
  13: 'Indústria',
  14: 'Indústria',
  15: 'Indústria',
  16: 'Indústria',
  17: 'Indústria',
  18: 'Indústria',
  19: 'Indústria',
  20: 'Indústria',
  21: 'Indústria',
  22: 'Indústria',
  23: 'Indústria',
  24: 'Indústria',
  25: 'Indústria',
  26: 'Indústria',
  27: 'Indústria',
  28: 'Indústria',
  29: 'Indústria',
  30: 'Indústria',
  31: 'Indústria',
  32: 'Indústria',
  33: 'Indústria',
  35: 'Energia e Utilities',
  36: 'Água e Saneamento',
  37: 'Água e Saneamento',
  38: 'Água e Saneamento',
  39: 'Água e Saneamento',
  41: 'Construção',
  42: 'Construção',
  43: 'Construção',
  45: 'Comércio',
  46: 'Comércio',
  47: 'Comércio',
  49: 'Transporte e Logística',
  50: 'Transporte e Logística',
  51: 'Transporte e Logística',
  52: 'Transporte e Logística',
  53: 'Transporte e Logística',
  55: 'Hospedagem e Alimentação',
  56: 'Hospedagem e Alimentação',
  58: 'Tecnologia e Comunicação',
  59: 'Tecnologia e Comunicação',
  60: 'Tecnologia e Comunicação',
  61: 'Tecnologia e Comunicação',
  62: 'Tecnologia e Comunicação',
  63: 'Tecnologia e Comunicação',
  64: 'Financeiro e Seguros',
  65: 'Financeiro e Seguros',
  66: 'Financeiro e Seguros',
  68: 'Imobiliário',
  69: 'Serviços Profissionais',
  70: 'Serviços Profissionais',
  71: 'Serviços Profissionais',
  72: 'Serviços Profissionais',
  73: 'Serviços Profissionais',
  74: 'Serviços Profissionais',
  75: 'Serviços Profissionais',
  77: 'Serviços Administrativos',
  78: 'Serviços Administrativos',
  79: 'Serviços Administrativos',
  80: 'Serviços Administrativos',
  81: 'Serviços Administrativos',
  82: 'Serviços Administrativos',
  84: 'Administração Pública',
  85: 'Educação',
  86: 'Saúde',
  87: 'Saúde',
  88: 'Saúde',
  90: 'Cultura, Esporte e Lazer',
  91: 'Cultura, Esporte e Lazer',
  92: 'Cultura, Esporte e Lazer',
  93: 'Cultura, Esporte e Lazer',
  94: 'Serviços Pessoais',
  95: 'Serviços Pessoais',
  96: 'Serviços Pessoais',
  97: 'Serviços Domésticos',
  99: 'Organismos Internacionais',
};

const PORTE_MAP: Record<string, { label: string; faixa: string }> = {
  MEI: { label: 'MEI', faixa: '1 funcionário' },
  'MICRO EMPRESA': { label: 'Micro Empresa (ME)', faixa: '1 a 9 funcionários' },
  'EMPRESA DE PEQUENO PORTE': { label: 'Pequeno Porte (EPP)', faixa: '10 a 49 funcionários' },
  DEMAIS: { label: 'Médio / Grande Porte', faixa: '50 ou mais funcionários' },
};

export function mapCnaeToSegment(cnae: number): string {
  const division = parseInt(cnae.toString().substring(0, 2));
  return CNAE_SEGMENTS[division] ?? 'Outros';
}

export function mapPorteToLabel(porte: string): string {
  return PORTE_MAP[porte]?.label ?? porte;
}

export function mapPorteToFaixa(porte: string): string {
  return PORTE_MAP[porte]?.faixa ?? 'Não informado';
}
